# Generated by Django 4.0.4 on 2022-04-25 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_attribut', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JeuDeDonnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.FileField(upload_to='media/dataset')),
                ('taille', models.IntegerField()),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentAttribut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('nom_op', models.CharField(max_length=255)),
                ('attribut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.attribut')),
                ('jeu_de_donnees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.jeudedonnees')),
            ],
        ),
        migrations.AddField(
            model_name='attribut',
            name='jeu_de_donnees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.jeudedonnees'),
        ),
    ]
