# Generated by Django 4.0.4 on 2022-04-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jeudedonnees',
            old_name='nom',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='jeudedonnees',
            name='taille',
            field=models.IntegerField(null=True),
        ),
    ]
