# Generated by Django 3.2.8 on 2022-06-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_jeudedonneesmodel_clusters'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeudedonneesmodel',
            name='nb_clusters',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
