# Generated by Django 4.0.4 on 2022-04-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_nom_jeudedonnees_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeudedonnees',
            name='nom',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
