# Generated by Django 3.2.8 on 2022-06-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_jeudedonneesmodel_nb_clusters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeudedonneesmodel',
            name='clusters',
            field=models.FileField(null=True, upload_to='media/clusters'),
        ),
        migrations.AlterField(
            model_name='jeudedonneesmodel',
            name='nb_clusters',
            field=models.IntegerField(default=0),
        ),
    ]
